### PR TITLE
implement start minimized to tray option

### PR DESCRIPTION
**Pull request by termermc**
This implements an option to start the application minimized to tray. Useful for setups (like my own) where the application automatically opens on system startup.

### CODE REVIEW

**Comment by reesericci** [comment]
this would be AMAZING!

**Comment by reesericci** [comment]
building now

**Comment by jerrod-lankford** [comment]
Sorry i havent really been paying much attention to this repo. If you can make this a checkbox instead of a yes/no dropdown then i will merge

**Comment by termermc** [comment]
Done

**Pull request merged**
