### PR TITLE
new theme (DarkPlus)

### PR DESCRIPTION
**Pull request by mathsmathsmaths**
I found about this app today and I'm very happy :) Decided to make a small contribution

Screenshot:
ss

### CODE REVIEW

**Comment by mathsmathsmaths** [comment]
Final draft:

darkplustheme

**Comment by Sharkgamedev** [comment]
+1 from me. Building from @mathsmathsmaths fork so I can start using this right away!

**Comment by mathsmathsmaths** [comment]
I hope you enjoy! if something doesn't look right, just say so on this thread, or open a pull request/issue on my fork.

Thanks!

**Comment by termermc** [comment]
I really like this, it would be great to add

**Comment by raulvasquez** [comment]
Nice!

**Pull request merged**
